name: Create Sentry release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # We need the previous commit to compare versions
      
      - name: Check if version changed
        id: version_check
        run: |
          PREV_VERSION=$(git show HEAD~1:package.json | grep '"version":' | cut -d'"' -f4)
          CURR_VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
          if [ "$PREV_VERSION" != "$CURR_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREV_VERSION to $CURR_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version did not change"
          fi
      
      - name: Get package version
        if: steps.version_check.outputs.version_changed == 'true'
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create Sentry release
        if: steps.version_check.outputs.version_changed == 'true'
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          release: ${{ steps.package_version.outputs.version }}
